### ISSUE TITLE
change /nfshome -> /storage in jupyter config

### ISSUE THREAD

**Issue by jpata** [cmscaltech/gpuservers#11]
Notebooks open by default still in /nfshome:

https://github.com/cmscaltech/gpuservers/blob/master/jupyter/jupyter_notebook_config_S.py#L266

**Comment by jpata** [comment]
For the moment changed by hand on `/storage/group/gpu/software/gpuservers/jupyter/jupyter_notebook_config_S.py` to make sure students are not stuck.

**Comment by vlimant** [comment]
9950cb18514ab5057f210bf5acf76c10eb2e0218 
not too sure on whether people take advantage of having access to /storage/user/ instead of only /storage/user/$USER

**Comment by vlimant** [comment]
took the chance at having jupyter start with jupyterlab 4ae2908697689e765ee79f50f27eb827a30bc311

**Comment by jpata** [comment]
Thanks, seems fixed!
