### ISSUE TITLE
Ports to be open based on UID

### ISSUE THREAD

**Issue by juztas** [cmscaltech/gpuservers#16]
It would be nice that ports assigned to user depend on uid. In that case you would not need to do manually edit file an add port for each user. 

e.g. I am unable to use jupyter notebook, because I am not on that list.

**Comment by vlimant** [comment]
#18 should do it

**Comment by juztas** [comment]
https://github.com/cmscaltech/puppet-centos7/pull/946 was merged. So now ports based on uid are open (also 8k-8.2k are also open so far) Will create another pull request to remove them

**Comment by juztas** [comment]
once start to use UID, lets merge this one: https://github.com/cmscaltech/puppet-centos7/pull/947

**Comment by vlimant** [comment]
now, let's not merge the blocking of ports 8k-8.2k just yet, as it requires people to restart their notebook server.

**Comment by juztas** [comment]
We can do check after 1 week (if none are in use, just merge then)

**Comment by vlimant** [comment]
email send ; please merge cmscaltech/puppet-centos7#947 on Friday noon PST @juztas

**Comment by juztas** [comment]
awesome. Will do!

**Comment by juztas** [comment]
Done. Thanks!
