### ISSUE TITLE
ROOT built for python3

### ISSUE THREAD

**Issue by thongonary** [cmscaltech/gpuservers#2]
https://root-forum.cern.ch/t/pyroot-import-error-pyinit-libpyroot/16263/15
We need a separated build of ROOT for python3.

**Comment by vlimant** [comment]
What do you need root for ? With uproot around the corner, I was actually thinking to remove root from the server. Depends on use case

**Comment by thongonary** [comment]
I don't know about uproot. I just need to use some ROOT library (TH1, TEfficiency, etc.)

**Comment by thongonary** [comment]
Please install uproot then (and don't remove root)

**Comment by vlimant** [comment]
http://uproot.readthedocs.io/en/latest/ is not going to help making plots

**Comment by thongonary** [comment]
I know... I need it for different purposes.
