### ISSUE TITLE
Can we have a test machine with sudo access to build singularity? 

### ISSUE THREAD

**Issue by thongonary** [cmscaltech/gpuservers#8]
I need to build a singularity image, but the only Linux machine I have root/sudo access is pccitX at CERN, which uses an old SLC version (SLC 6.5) and couldn't build the image due to some OS incompatibility https://github.com/sylabs/singularity/issues/473

Can we have a test machine at the Caltech cluster that we have sudo access and be able to build the image? Otherwise the users have to rely on the admins to update the singularity image, which is very suboptimal.

**Comment by vlimant** [comment]
no root access to anyone
https://github.com/cmscaltech/gpuservers/blob/master/README.md#building-an-image

**Comment by thongonary** [comment]
I'm asking sudo access, not root.
