### ISSUE TITLE
Sudo access to build singularity

### ISSUE THREAD

**Issue by thongonary** [cmscaltech/gpuservers#9]
Continuation of https://github.com/cmscaltech/gpuservers/issues/8 

We need sudo access to build the image. If not on the main machine (imperium etc.) then at least in a test machine.

**Comment by juztas** [comment]
p.s. users do have sudo access on gpu machines to use singularity command

**Comment by juztas** [comment]
for reference: https://github.com/cmscaltech/puppet-centos7/pull/552/files

**Comment by thongonary** [comment]
Thanks. It would be nice to update this information -- No one told me it was implemented and last time Joosep told me I need to create singularity in another Linux machine. https://github.com/cmscaltech/gpuservers/pull/3 
Would have saved me a day :)
